######################################################
# Install/Setup Grafana
######################################################
- name: Install software
  apt:
    name: ['adduser','libfontconfig1']
    state: present

- name: Download Grafana
  get_url:
    url: "{{ grafana_dl_url }}"
    dest: "/tmp/grafana_{{ grafana_version }}_amd64.deb"

- name: Install Grafana
  apt:
    deb: "/tmp/grafana_{{ grafana_version }}_amd64.deb"

- name: Copy Node exporter dashboard
  ansible.builtin.copy:
    src: 'conf/metrics/grafana/node-exporter-full_rev25.json'
    dest: '/etc/grafana/provisioning/dashboards'
    owner: root
    group: grafana
    mode: 0640

- name: Start Grafana
  service:
    name: "grafana-server"
    enabled: yes
    state: restarted

- name: Copy dashboards
sdfsf
sdf
sdfds
f
ds
fs
dfs

- name: Grafana Health Check
  uri:
    url: "http://127.0.0.1:3000/login"
    follow_redirects: none
    method: GET
  register: grafana_result
  until: grafana_result.status == 200
  retries: 720
  delay: 5
  no_log: true