####################################################################
# Setup NGINX
####################################################################
- name: Copy NGINX exporter config
  template:
    src: "conf/ansible/nginx/nginx-exporter.conf"
    dest: "/etc/nginx/conf.d/nginx-exporter.conf"
    owner: root
    group: root
    mode: 0600

- name: Restart NGINX
  service:
    name: nginx
    enabled: yes
    state: restarted

- name: nginx health check
  uri:
    url: "http://127.0.0.1:8080/stub_status"
    follow_redirects: none
    method: GET
    status_code: 200
  register: nginx_result
  until: nginx_result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds

####################################################################
# Install/Setup NGINX exporter
####################################################################
- name: Create NGINX exporter Group
  group:
    name: nginxexporter
    state: present

- name: Create NGINX exporter User
  user:
    name: nginxexporter
    groups: nginxexporter
    shell: /usr/sbin/nologin
    state: present

- name: Stat NGINX exporter
  stat:
    path: "/usr/local/bin/nginx_exporter"
  register: nginx_exporter_install

- name: Download NGINX exporter
  get_url:
    url: "{{ nginx_exporter_dl_url }}"
    dest: "/tmp/nginx_exporter-{{ nginx_exporter_version }}.linux-amd64.tar.gz"
  when: not nginx_exporter_install.stat.exists

- name: Extract NGINX exporter
  ansible.builtin.unarchive:
    src: "/tmp/nginx_exporter-{{ nginx_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: not nginx_exporter_install.stat.exists

- name: Move NGINX exporter binary
  ansible.builtin.copy:
    src: "/tmp/nginx-prometheus-exporter"
    dest: "/usr/local/bin/nginx_exporter"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
  when: not nginx_exporter_install.stat.exists

- name: Copy NGINX exporter service
  template:
    src: "conf/ansible/metric_exporters/nginx_exporter.service"
    dest: "/etc/systemd/system/nginx-exporter.service"
    owner: "root"
    group: "root"
    mode: 0600

- name: Start NGINX exporter service
  service:
    name: "nginx-exporter"
    enabled: yes
    state: restarted

- name: Allow NGINX exporter (9113/TCP)
  community.general.ufw:
    rule: allow
    port: "{{ nginx_exporter_port }}"
    proto: tcp

##########################################################################
# Healthcheck
##########################################################################
- name: nginx exporter health check
  uri:
    url: "http://127.0.0.1:{{ nginx_exporter_port }}"
    follow_redirects: none
    method: GET
    status_code: 200
  register: nginx_result
  until: nginx_result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds