##########################################################################
# Create osctrl user and group
##########################################################################
- name: Create osctrl group
  group:
    name: 'osctrl'
    state: present

- name: Create osctrl user
  user:
    name: osctrl
    groups: osctrl
    shell: /usr/sbin/nologin

##########################################################################
# Create osctrl config directory
##########################################################################
- name: stat /etc/osctrl directory
  ansible.builtin.stat:
    path: /etc/osctrl
  register: osctrl_config_dir

- name: Create /etc/osctrl directory
  ansible.builtin.file:
    path: "/etc/osctrl"
    state: directory
    recurse: yes
    owner: root
    group: root
  when: not osctrl_config_dir.stat.exists

##########################################################################
# Create osctrl log directory
##########################################################################
- name: stat /var/log/osctrl directory
  ansible.builtin.stat:
    path: /var/log/osctrl
  register: osctrl_log_dir

- name: Create /var/log/osctrl directory
  ansible.builtin.file:
    path: "/var/log/osctrl"
    state: directory
    recurse: yes
    owner: osctrl
    group: adm
  when: not osctrl_log_dir.stat.exists


##########################################################################
# Copy osctrl configs
##########################################################################
- name: Copy osctrl DB config
  template:
    src: "conf/ansible/osctrl/db.json"
    dest: "/etc/osctrl/db.json"
    owner: root
    group: osctrl
    mode: '0640'

- name: Copy osctrl Redis config
  template:
    src: "conf/ansible/osctrl/redis.json"
    dest: "/etc/osctrl/redis.json"
    owner: root
    group: osctrl
    mode: '0640'

##########################################################################
# Get osctrl source code
##########################################################################
- name: Stat Osctrl source code
  stat:
    path: "/tmp/osctrl-{{ osctrl_version }}"
  register: osctrl_source_code

- name: Download Osctrl source code
  get_url:
    url: "{{ osctrl_web_assets }}"
    dest: "/tmp/{{ osctrl_version }}.tar.gz"
  when: not osctrl_source_code.stat.exists

- name: Extract Osctrl source code
  ansible.builtin.unarchive:
    src: "/tmp/{{ osctrl_version }}.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: not osctrl_source_code.stat.exists