##########################################################################
# Create environment
##########################################################################
- name: Stat osctrl-cli binary
  ansible.builtin.stat:
    path: /usr/local/bin/osctrl-cli
  register: osctrl_cli_binary

- name: Create osctrl environment
  shell: >
    /usr/local/bin/osctrl-cli 
    --db
    --db-file /etc/osctrl/db.json
    env add
    --name {{ osctrl_env }}
    --hostname {{ hostname }}.{{ base_domain }}
  ignore_errors: yes 
  

##########################################################################
# Create admin user
##########################################################################
- name: Create osctrl admin user
  shell: >
    /usr/local/bin/osctrl-cli 
    --db
    --db-file /etc/osctrl/db.json
    user add
    --admin
    --username {{ osctrl_username }}
    --password {{ osctrl_password }}
    --environment {{ osctrl_env }}
    --fullname {{ osctrl_username }}
  ignore_errors: yes 
