##########################################################################
# Install/Setup Osctrl-cli
##########################################################################
- name: Stat osctrl-cli binary
  ansible.builtin.stat:
    path: /usr/local/bin/osctrl-cli
  register: osctrl_cli_binary

- name: Download and install osctrl-cli v{{ osctrl_version }}
  apt:
    deb: "{{ osquery_deb_dl_url }}/osctrl-cli_v{{ osctrl_version }}_amd64.deb"
  when: not osctrl_cli_binary.stat.exists

##########################################################################
# Healthcheck
##########################################################################
- name: osctrl-cli healthcheck
  shell: "/usr/local/bin/osctrl-cli --db --db-file /etc/osctrl/db.json check"