####################################################################
# Install/Setup Redis exporter
####################################################################
- name: Create redis user for redis_exporter 
  shell: |
    echo "ACL SETUSER redisexporter +client +ping +info +config|get +cluster|info +slowlog +latency +memory +select +get +scan +xinfo +type +pfcount +strlen +llen +scard +zcard +hlen +xlen +eval allkeys on >{{ redis_exporter_password }}" | redis-cli -a {{ redis_password }}

####################################################################
# Install Redis exporter
####################################################################
- name: Create Redis exporter Group
  group:
    name: redis_exporter
    state: present

- name: Create Redis exporter User
  user:
    name: redis_exporter
    groups: redis_exporter
    shell: /usr/sbin/nologin
    state: present

- name: Stat Redis exporter
  stat:
    path: "/usr/local/bin/redis_exporter"
  register: redis_exporter_install

- name: Download redis exporter
  get_url:
    url: "{{ redis_exporter_dl_url }}"
    dest: "/tmp/redis_exporter-{{ redis_exporter_version }}.linux-amd64.tar.gz"
  when: not redis_exporter_install.stat.exists

- name: Extract redis exporter
  ansible.builtin.unarchive:
    src: "/tmp/redis_exporter-{{ redis_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes
  when: not redis_exporter_install.stat.exists

- name: Move redis exporter binary
  ansible.builtin.copy:
    src: "/tmp/redis_exporter-v{{ redis_exporter_version }}.linux-amd64/redis_exporter"
    dest: "/usr/local/bin/redis_exporter"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
  when: not redis_exporter_install.stat.exists

- name: Copy redis exporter service
  template:
    src: "conf/ansible/metric_exporters/redis_exporter.service"
    dest: "/etc/systemd/system/redis-exporter.service"
    owner: "root"
    group: "root"
    mode: 0600


####################################################################
# Setup Redis exporter
####################################################################
- name: Create config directory
  file:
    path: "/etc/redis_exporter"
    owner: root
    group: root
    state: directory

- name: Copy redis exporter password
  template:
    src: "conf/ansible/metric_exporters/redis_exporter_password.json"
    dest: "/etc/redis_exporter/password.json"
    owner: root
    group: redis_exporter
    mode: 0640


- name: Start redis exporter service
  service:
    name: "redis-exporter"
    enabled: yes
    state: restarted

##########################################################################
# Healthcheck
##########################################################################
- name: redis_exporter health check
  uri:
    url: "http://127.0.0.1:{{ redis_exporter_port }}/metrics"
    follow_redirects: none
    method: GET
    status_code: 200
  register: nginx_result
  until: nginx_result.status == 200
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds  