##########################################################################
# Install/Setup Redis
##########################################################################
- name: Install Redis
  apt:
    name: ["redis={{ redis_version}}"]

- name: Set Redis password
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: "# requirepass"
    line: "requirepass {{ redis_password }}"

- name: Restart Redis
  service:
    name: "redis-server"
    state: restarted
    enabled: yes

##########################################################################
# Healtcheck
##########################################################################
- name: Redis healthcheck
  shell: "echo 'ping' | redis-cli"